name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check formatting and Clippy
<<<<<<< HEAD
      run: ./ci.sh
=======
      run: sh -x ./ci.sh
>>>>>>> 5950168159f0e041f24f59bfa9f9e6ee986efa38
